# STC Jawwy

In [3]:
"""
Here we install libraries that are not installed by default 
Example:  pyslsb
Feel free to add any library you are planning to use.
"""
%pip install pyxlsb

Requirement already satisfied: pyxlsb in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (1.0.10)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Import the required libraries 
"""
Please feel free to import any required libraries as per your needs
"""
import pandas as pd     # provides high-performance, easy to use structures and data analysis tools
import pyxlsb           # Excel extention to read xlsb files (the input file)
import numpy as np      # provides fast mathematical computation on arrays and matrices

# Jawwy dataset
The dataset consists of meta details about the movies and tv shows as genre. 
Also details about Users activities, spent duration and if watching in High definition or standard definition. 
You have to analyse this dataset to find top insights, findings and to solve the four tasks assigned to you.

In [5]:
dataframe = pd.read_excel("stc TV Data Set_T1.xlsb",sheet_name="Final_Dataset")
# Please make a copy of dataset if you are going to work directly and make changes on the dataset
# you can use   df=dataframe.copy()

In [6]:
# check the data shape
dataframe.shape

(1048575, 13)

In [7]:
# display the first 5 rows 
dataframe.head()

,Column1,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,hd,original_name
0,1,42882,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,0,100 treets
1,3,42876,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,1,Moana
2,4,42957,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
3,5,42942,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
4,7,42923,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,1,Churchill

In [8]:
# Data Preprocessing on the input data
dataframe = dataframe.drop(columns=['Column1'], errors="ignore")         # dropping the index column
dataframe['program_name'] = dataframe['program_name'].str.strip()  # trim spaces in movies names to avoid misspellings in input data
dataframe['date_'] = pd.to_datetime(dataframe['date_'], unit='D', origin='30/12/1899')  # read date column as date data type
dataframe[['duration_seconds', 'season','episode','series_title','hd']] = dataframe[['duration_seconds', 'season','episode','series_title','hd']].apply(pd.to_numeric)  # read numeric columns as numeric data types
dataframe[['user_id_maped', 'program_name','program_class','program_desc','program_genre','original_name']] = dataframe[['user_id_maped', 'program_name','program_class','program_desc','program_genre','original_name']].astype(str) # read string columns as string data types

In [9]:
# display the dataset after applying data types
dataframe.head()

,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,hd,original_name
0,2017-05-27,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,0,100 treets
1,2017-05-21,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,1,Moana
2,2017-08-10,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
3,2017-07-26,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
4,2017-07-07,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,1,Churchill

In [10]:
# describe the numeric values in the dataset
dataframe.describe()

,date_,duration_seconds,season,episode,series_title,hd
count,1048575,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,2017-10-04 00:23:20,1.230957e+03,1.342139e+00,6.157952e+00,1.205922e-02,3.862728e-01
min,2017-03-14 00:00:00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2017-06-10 00:00:00,5.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2017-10-14 00:00:00,1.190000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
75%,2018-01-21 00:00:00,1.328000e+03,1.000000e+00,9.000000e+00,0.000000e+00,1.000000e+00
max,2018-04-30 00:00:00,1.461329e+06,2.300000e+01,2.820000e+02,1.000000e+00,1.000000e+00
std,NaN,6.821058e+03,2.104095e+00,1.222015e+01,1.091504e-01,4.868946e-01

In [11]:
# check if any column has null value in the dataset
dataframe.isnull().any()

date_               False
user_id_maped       False
program_name        False
duration_seconds    False
program_class       False
season              False
episode             False
program_desc         True
program_genre       False
series_title        False
hd                  False
original_name       False
dtype: bool

In [12]:
df=dataframe.copy()

In [13]:
dataframe = dataframe.dropna()

In [14]:
dataframe.info()

<class 'pandas.DataFrame'>
Index: 1034537 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   date_             1034537 non-null  datetime64[s]
 1   user_id_maped     1034537 non-null  str
 2   program_name      1034537 non-null  str
 3   duration_seconds  1034537 non-null  int64
 4   program_class     1034537 non-null  str
 5   season            1034537 non-null  int64
 6   episode           1034537 non-null  int64
 7   program_desc      1034537 non-null  str
 8   program_genre     1034537 non-null  str
 9   series_title      1034537 non-null  int64
 10  hd                1034537 non-null  int64
 11  original_name     1034537 non-null  str
dtypes: datetime64[s](1), int64(5), str(6)
memory usage: 102.6 MB

In [15]:
dataframe.isnull().any()

date_               False
user_id_maped       False
program_name        False
duration_seconds    False
program_class       False
season              False
episode             False
program_desc        False
program_genre       False
series_title        False
hd                  False
original_name       False
dtype: bool

In [16]:
dataframe.describe()

,date_,duration_seconds,season,episode,series_title,hd
count,1034537,1.034537e+06,1.034537e+06,1.034537e+06,1.034537e+06,1.034537e+06
mean,2017-10-03 15:49:32,1.233010e+03,1.334519e+00,6.165930e+00,1.222286e-02,3.842821e-01
min,2017-03-14 00:00:00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2017-06-11 00:00:00,5.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2017-10-13 00:00:00,1.190000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
75%,2018-01-20 00:00:00,1.330000e+03,1.000000e+00,9.000000e+00,0.000000e+00,1.000000e+00
max,2018-04-30 00:00:00,1.461329e+06,2.300000e+01,2.820000e+02,1.000000e+00,1.000000e+00
std,NaN,6.841556e+03,2.100225e+00,1.226151e+01,1.098794e-01,4.864253e-01

In [17]:
dataframe = dataframe.reset_index(drop=True)

In [18]:
dataframe.head()

,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,hd,original_name
0,2017-05-27,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,0,100 treets
1,2017-05-21,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,1,Moana
2,2017-08-10,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
3,2017-07-26,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
4,2017-07-07,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,1,Churchill

# Task 1
##### You are required to work on task one to study and HD flag for available dataset

In [19]:
# make a copy of the dataframe for working on task 1
df=dataframe.copy()

In [20]:
# Here we try to get the most watched movies (Total Views / Total Users Views / Total watch time)
# For series we concatenated the Session episode to differentiate between episodes 
grouped=df.copy()
grouped.loc[grouped['program_class'] == 'SERIES/EPISODES', 'program_name'] = grouped['program_name']+'_SE'+grouped['season'].astype(str)+'_EP'+grouped['episode'].astype(str)

grouped = grouped.groupby(['program_name','program_class'])\
.agg({'user_id_maped': [('co1', 'nunique'),('co2', 'count')],\
      'duration_seconds': [('co3', 'sum')] }).reset_index()

grouped.columns = ['program_name','program_class','No of Users who Watched', 'No of watches', 'Total watch time in seconds']
grouped['Total watch time in houres']=grouped['Total watch time in seconds']/3600
grouped = grouped.drop(columns=['Total watch time in seconds'])
grouped = grouped.sort_values(by=['Total watch time in houres', 'No of watches','No of Users who Watched'], ascending=False).reset_index(drop=True)

In [21]:
# show the result
grouped.head(35)

,program_name,program_class,No of Users who Watched,No of watches,Total watch time in houres
0,The Boss Baby,MOVIE,3389,24047,2961.350833
1,The Amazing pider-Man,MOVIE,1011,2877,1966.119167
2,The Expendables,MOVIE,853,2119,1961.159444
3,Moana,MOVIE,2173,8081,1706.176944
4,Trolls,MOVIE,2613,13793,1601.023056
5,Bean,MOVIE,949,3617,1423.955000
6,The murfs,MOVIE,867,3132,1342.141111
7,Hotel Transylvania,MOVIE,491,1947,1096.533611
8,Cloudy With a Chance of Meatballs,MOVIE,683,2076,948.674722
9,The Man With The Iron Fists,MOVIE,707,2505,859.626389
10,Salt,MOVIE,563,1082,767.392778
11,Unbroken,MOVIE,625,1429,763.078333
12,ParaNorman,MOVIE,614,1746,747.065556
13,Youm Maloosh Lazma,MOVIE,1131,2278,718.109722
14,Ferdinand,MOVIE,1276,6811,714.076389
15,White Chicks,MOVIE,307,916,711.840833
16,Jurassic Park,MOVIE,504,1192,693.394444
17,The November Man,MOVIE,494,1219,679.492222
18,Total Recall,MOVIE,587,1108,661.820000
19,Robin Hood,MOVIE,588,1209,643.935000
20,Public Enemies,MOVIE,368,716,634.035000
21,Daddy Day Camp,MOVIE,263,647,625.338333
22,Oblivion,MOVIE,790,1678,609.391111
23,Blitz,MOVIE,562,1200,570.521944
24,War for the Planet of the Apes,MOVIE,879,2028,567.597778
25,Inside Man,MOVIE,532,1567,560.386111
26,Bad Boys,MOVIE,438,871,559.277500
27,Easy A,MOVIE,513,990,557.068611
28,Battleship,MOVIE,634,1324,552.857222
29,Baywatch,MOVIE,2062,7436,548.995556
30,Police tory,MOVIE,409,737,520.077222
31,Blindspot Erase Weary Youth_SE1_EP13,SERIES/EPISODES,125,197,516.015556
32,47 Ronin,MOVIE,521,1701,515.014722
33,Alien: Covenant,MOVIE,1520,4260,507.180000
34,The Mermaid Princess,MOVIE,2182,7525,503.111111

In [22]:
%pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
%pip install plotly

Requirement already satisfied: plotly in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from plotly) (2.18.0)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from plotly) (26.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
# we import Visualization libraries 
# you can ignore and use any other graphing libraries 
import matplotlib.pyplot as plt # a comprehensive library for creating static, animated, and interactive visualizations
import plotly #a graphing library makes interactive, publication-quality graphs. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [25]:
%pip install nbformat

Requirement already satisfied: nbformat in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.2)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# plot top 10 Programs 
fig = px.pie(grouped.head(10), values='Total watch time in houres', names='program_name',\
             hover_data=['program_class'],title='top 10 programs in total watch time in houres')
fig.show()

In [15]:
# Here we try to study the customer experience against Program class
grouped=df.copy()
grouped = grouped.groupby('program_class')\
.agg({'user_id_maped': [('co1', 'nunique'),('co2', 'count')],\
      'duration_seconds': [('co3', 'sum')] }).reset_index()
grouped.columns = ['program_class','No of Users who Watched', 'No of watches', 'Total watch time in seconds']
grouped['Total watch time in houres']=grouped['Total watch time in seconds']/3600
grouped = grouped.drop(columns=['Total watch time in seconds'])
grouped = grouped.sort_values(by=['Total watch time in houres', 'No of watches','No of Users who Watched'], ascending=False).reset_index(drop=True)

In [16]:
# show the result
grouped.head()

,program_class,No of Users who Watched,No of watches,Total watch time in houres
0,SERIES/EPISODES,3901,560174,255097.787500
1,MOVIE,11355,488401,103444.145556

In [17]:
# plot the total watch time against total number of users and report your findings
fig = px.pie(grouped, values='Total watch time in houres', names='program_class',\
             hover_data=['program_class'],title='Total duration spent by program_class')
fig2 = px.pie(grouped, values='No of Users who Watched', names='program_class',\
             hover_data=['program_class'],title='Total Users watching by program_class')

fig.update_traces(sort=False)
fig2.update_traces(sort=False)
fig.show()
fig2.show()

In [27]:
"""
TODO study the relation and user's behaviour Against HD flag, feel free to include any comparison 
"""
df.head()

,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,hd,original_name
0,2017-05-27,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,0,100 treets
1,2017-05-21,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,1,Moana
2,2017-08-10,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
3,2017-07-26,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
4,2017-07-07,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,1,Churchill

In [37]:
# study the relation and user's behaviour Against HD flag
# first, we study if HD quality make people watch for longer

grouped = df.copy()
grouped = grouped.groupby("hd").agg({'user_id_maped' : [('co1' , 'nunique'),('co2' , 'count')],\
                                    'duration_seconds' : [('co3' , 'sum')] }).reset_index()
grouped.columns = ['HD_Flag' , 'No of Users', 'No of Watches' , 'Total watch time in seconds']
grouped['Total watch time in hours'] = grouped['Total watch time in seconds'] / 3600
grouped = grouped.drop(columns=['Total watch time in seconds'])
grouped['Avg hours per watch'] = grouped['Total watch time in hours'] / grouped['No of Watches']
grouped = grouped.sort_values(by=['Avg hours per watch'],ascending=False).reset_index(drop=True)
grouped

,HD_Flag,No of Users,No of Watches,Total watch time in hours,Avg hours per watch
0,0,6715,636983,265340.077778,0.416558
1,1,10960,397554,88991.706667,0.223848

In [45]:
quality_map = {0: 'SD', 1: 'HD'}
grouped['Quality_Label'] = grouped['HD_Flag'].map(quality_map)

fig = px.pie(grouped,values='Total watch time in hours', names='Quality_Label', hover_data=['Quality_Label'], title='Total duration spent by Quality')
fig2 = px.pie(grouped,values='No of Users', names='Quality_Label', hover_data=['Quality_Label'], title='Total Users Watching by Quality')

fig.show()
fig2.show()

In [64]:
grouped = df.copy()
grouped.loc[grouped['program_class'] == 'SERIES/EPISODES', 'program_name'] = \
    grouped['program_name'] + '_SE' + grouped['season'].astype(str) + '_EP' + grouped['episode'].astype(str)

# We map the HD flag to SD/HD labels first for better readability
grouped['hd'] = grouped['hd'].map({0: 'SD', 1: 'HD'})
grouped = grouped.groupby(['program_genre','hd'])\
    .agg({'user_id_maped' : [('co1' , 'nunique') , ('co2' , 'count')],\
          'duration_seconds' : [('co3' , 'sum')] }).reset_index()
grouped.columns = ['program_genre' , 'Quality' , 'No of Users who Watched', 'No of watches', 'Total watch time in seconds']
grouped['Total watch time in hours'] = grouped['Total watch time in seconds'] / 3600
grouped = grouped.drop(columns=['Total watch time in seconds'])
grouped.sort_values(by=['Total watch time in hours' , 'No of watches', 'No of Users who Watched'], ascending=False).reset_index(drop=True)
grouped['program_genre'] = grouped['program_genre'].replace('SERIES_NOT_ADDED_UNDER_ANY_GENRE', 'Other')
grouped

,program_genre,Quality,No of Users who Watched,No of watches,Total watch time in hours
0,Action,HD,6269,75484,24146.891667
1,Action,SD,4489,98234,52012.853333
2,Adventure,HD,1,1,0.001111
3,Adventure,SD,112,238,44.588333
4,Animation,HD,7796,146223,21084.934444
5,Animation,SD,3704,250057,67211.413889
6,Biography,HD,3330,11496,2408.037222
7,Biography,SD,974,4511,273.099722
8,Comedy,HD,5563,61054,21367.909167
9,Comedy,SD,4026,75091,32710.219167
10,Crime,HD,780,2315,901.806944
11,Crime,SD,190,916,564.947500
12,Documentary,HD,1955,9939,745.475556
13,Documentary,SD,892,3266,1494.045833
14,Drama,HD,5489,46397,10254.843889
15,Drama,SD,3395,106670,67385.951389
16,Family,HD,1218,3827,969.505000
17,Family,SD,1535,22841,5499.024722
18,Horror,HD,4547,25905,3046.179167
19,Horror,SD,2263,48911,22636.638333
20,Romance,SD,115,512,391.432778
21,Other,SD,67,105,135.429167
22,Sci-Fi,HD,96,134,2.038889
23,Sci-Fi,SD,234,1188,726.826389
24,Thriller,HD,3361,14779,4064.083611
25,Thriller,SD,2486,24435,14253.512222
26,Wrestling,SD,7,8,0.095000

In [68]:
fig = px.bar(grouped, 
             x='program_genre', 
             y='Total watch time in hours', 
             color='Quality', 
             barmode='group',
             title='Total Watch Time by Genre and Quality',
             color_discrete_map={'HD':'gold', 'SD':'royalblue'})

fig2 = px.bar(grouped, 
             x='program_genre', 
             y='No of Users who Watched', 
             color='Quality', 
             barmode='group',
             title='Number of Unique Users by Genre and Quality',
             color_discrete_map={'HD':'gold', 'SD':'royalblue'})

fig.show()
fig2.show()